const semesterSeven = [
  {
    question: "Define round-off error?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "What is truncation error?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "Define divided differences.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "State Newton's Forward Interpolation Formula.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "Write one application of interpolation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "What is the order of convergence of Newton-Raphson method?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "Explain different types of errors in numerical computation.",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "sC-342",
    Subject: "numerical computing",
    category: "long",
    marks: 10,
  },
  {
    question: "Discuss propagation of errors.",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "sC-342",
    Subject: "numerical computing",
    category: "long",
    marks: 10,
  },
  {
    question: "Define fixed point iteration.",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "sC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "Write Simpson's 1/3 rule formula.",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "sC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "What is numerical differentiation?",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "sC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "Define Gaussian Quadrature.",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "sC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "What is Richardson extrapolation?",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "sC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "State one advantage of Bisection method.",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    id: 2,
    question:
      "Derive Trapezoidal Rule with error term and apply it to evaluate a definite integral.",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "long",
    marks: 10,
  },
  {
    id: 3,
    question:
      "Explain numerical differentiation using Newton's Forward Difference Formula.",
    index: false,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "long",
    marks: 10,
  },
  {
    question: "What is machine epsilon?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "Define computer arithmetic.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "What is backward difference?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "Write Stirling's interpolation formula.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "What is the secant method?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question: "Define convergence.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "short",
    marks: 5,
  },
  {
    question:
      "Explain floating point representation and round-off errors in detail.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Using Newton's Backward Interpolation Formula, estimate the value of f(x).",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    CourseCode: "SC-342",
    Subject: "numerical computing",
    category: "long",
    marks: 10,
  },
  {
    question: "Define technical communication.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "What is the purpose of a preamble in a report?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Give two examples of electronic documents.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "What do you understand by 'classification and division'?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Write differences between paragraphs and sentences.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question:
      "Discuss the process of organizing information for a technical report.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Describe the characteristics of effective exposition with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "long",
    marks: 10,
  },
  {
    question: "What is casual analysis?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Define electronic communication.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "What is plagiarism?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Write short note on footnotes.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "What are empty words?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Compare and contrast abstracts and summaries.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "long",
    marks: 10,
  },
  {
    question: "What are progress reports? Explain how they are written.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    CourseCode: "GE-261",
    Subject: "technical and business writing",
    category: "long",
    marks: 10,
  },
  {
    question: "What is a summary?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Write two purposes of abstracts.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Define document design.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Give meaning of classification.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "What are appendices?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "GE-261",
    Subject: "technical and business writing",
    category: "short",
    marks: 5,
  },
  {
    question: "Explain the conventions of written technical communication.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "GE-261",
    Subject: "technical and business writing",
    category: "long",
    marks: 10,
  },
  {
    question: "Discuss the steps for constructing a formal outline.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "GE-261",
    Subject: "technical and business writing",
    category: "long",
    marks: 10,
  },
  {
    question: "Define Software Project Management.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "What are PMI Process Groups?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "Explain risk control in project management.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "What is software effort estimation?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "Define configuration management.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question:
      "Discuss the key concepts and importance of software project management.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "long",
    marks: 10,
  },
  {
    question: "Explain project planning and project evaluation techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "long",
    marks: 10,
  },
  {
    question: "What do you understand by project selection?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "Define PMI framework.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "What is activity planning?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "Mention two software project management tools.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "What is risk mitigation?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "What does resource allocation involve?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question:
      "What is configuration management? Explain environment for configuration control and maintenance.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Explain PMI's Knowledge Areas and their role in project success.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Discuss the role of review and evaluation processes in project monitoring.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "long",
    marks: 10,
  },
  {
    question: "Define project life cycle.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "What is project review?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "What is risk control?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "Define schedule evaluation.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "What is project monitoring?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question: "Write short note on configuration control.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "short",
    marks: 5,
  },
  {
    question:
      "Discuss the importance of understanding organizational structure in software project management.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "long",
    marks: 10,
  },
  {
    question: "Explain project planning tools and techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Describe approaches to software effort estimation with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-431",
    Subject: "software project management",
    category: "long",
    marks: 10,
  },
  {
    question: "What is Acceptance Testing?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "List any four Testing Techniques.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "Explain Model-based Testing in brief.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "What is the purpose of Testing Documentation?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "Define In-Process MCS.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question:
      "Explain the software testing life cycle in detail. Describe the major phases and their significance in ensuring quality.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Discuss Software Reliability Models. Explain the Exponential Growth Model and how it is useful in testing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Define Software Quality Attributes. Explain how these attributes influence Quality Engineering in software development.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2022,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
  {
    question: "What is Test Automation?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "Differentiate between Unit Testing and Integration Testing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "Define Quality Models.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "What are Product Quality Metrics?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "Mention two In-Process Quality Management tools.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question:
      "Describe the Test Planning Process and explain why test planning is crucial for software quality assurance.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
  {
    question: "Discuss Domain and Combinatorial Testing with examples.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Explain Specification Based Testing and how it differs from other testing approaches.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2023,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
  {
    question: "What are Testing Strategies?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "Define Software Inspections.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "What is Effort/Outcome Model?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "Why is Historical Data Recording important in testing?",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question: "Explain the purpose of Test Cases.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "short",
    marks: 5,
  },
  {
    question:
      "Explain the Testing Scopes and Testing Philosophies used in software testing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Discuss the role of Software Reviews and Inspections in software quality assurance.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
  {
    question:
      "Explain System Testing and how scenarios and use-cases are used for testing.",
    index: true,
    trim: true,
    type: "past-paper",
    year: 2024,
    courseCode: "EC-432",
    Subject: "software quality assurance",
    category: "long",
    marks: 10,
  },
];

export { semesterSeven };
