const shortQuestions1 = [
  { 
    id: 1, 
    question: "What is meant by software development?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 2, 
    question: "What is meant by Software development lifecycle?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 3, 
    question: "What is meant by framework in software development?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 4, 
    question: "Name all the stages involved in SDLC.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 5, 
    question: "What is meant by requirement gathering? Also describe key activities involved in this phase.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 6, 
    question: "Differentiate between functional and non functional requirements.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 7, 
    question: "What is meant by design phase in SDLC? Also describe key activities involved in this phase.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 8, 
    question: "What is meant by coding?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 9, 
    question: "What is meant by development phase?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 10, 
    question: "What is meant by testing phase?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 11, 
    question: "What is meant by Deployment? Also describe main steps involved in this phase.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 12, 
    question: "Define maintenance.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 13, 
    question: "What is meant by software development methodologies?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 14, 
    question: "What is meant by software process models?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 15, 
    question: "What is the importance of software process models?", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 16, 
    question: "What is meant by Waterfall model?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 17, 
    question: "Name the main phases involved in Waterfall model.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 18, 
    question: "What are some benefits of Waterfall model.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 19, 
    question: "What are some limitations of Waterfall model.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 20, 
    question: "What is meant by agile methodology?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 21, 
    question: "Describe the main practices involved in agile methodology.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 22, 
    question: "What are some benefits of agile methodology?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 23, 
    question: "What are some limitations of agile methodology?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 24, 
    question: "What is meant by comprehensive project planning?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 25, 
    question: "What is meant by setting project timelines?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 26, 
    question: "What is meant by estimating cost in software development?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 27, 
    question: "What are some key factors involved in cost estimation of software?", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 28, 
    question: "What is meant by risk assessment and management?", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 29, 
    question: "Which steps are involved in risk assessment and management?", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 30, 
    question: "What is meant by Quality assurance?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 31, 
    question: "Define design patterns.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 32, 
    question: "Define singleton and factory pattern.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 33, 
    question: "Define Observer and Strategy pattern.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 34, 
    question: "What are some applications of design patterns in software design?", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 35, 
    question: "What is meant by Debugging?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 36, 
    question: "What are the tools and best practices for debugging?", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 37, 
    question: "Differentiate between unit and integration testing.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 38, 
    question: "Differentiate between system and acceptance testing.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 39, 
    question: "Define software development tools.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 40, 
    question: "Define language editor. Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 41, 
    question: "Define translators. Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 42, 
    question: "Define Debuggers. Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 43, 
    question: "Define Integrated Development Environment. Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 44, 
    question: "What is meant by online and offline platforms?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 45, 
    question: "What is meant by source code repositories?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 1,
  },
  { 
    id: 46, 
    question: "Explain why testing phase is important in the Software Development Lifecycle, and provide two reasons for its significance.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "ex-short",
    chapter: 1,
  },
  { 
    id: 47, 
    question: "Illustrate the concept of continuous integration in Agile methodology and discuss its importance in software development.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "ex-short",
    chapter: 1,
  },
  { 
    id: 48, 
    question: "Evaluate the main steps involved in risk assessment and management, and assess their importance in a software project.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "ex-short",
    chapter: 1,
  },
];

const longQuestions1 = [
  { 
    id: 1, 
    question: "Write a detailed note on SDLC.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "long",
    chapter: 1,
  },
  { 
    id: 2, 
    question: "Write a detailed note on Requirement Gathering.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "long",
    chapter: 1,
  },
  { 
    id: 3, 
    question: "Write a detailed note on Waterfall Model.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "long",
    chapter: 1,
  },
  { 
    id: 4, 
    question: "Write a detailed note on Agile methodology.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "long",
    chapter: 1,
  },
  { 
    id: 5, 
    question: "Imagine you are managing a project to develop a simple mobile application. Describe how you would use the agile methodology to handle this project.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "ex-long",
    chapter: 1,
  },
  { 
    id: 6, 
    question: "Discuss the importance of software development tools in the software development process.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "ex-long",
    chapter: 1,
  },
  { 
    id: 7, 
    question: "Explain the role of language editors, translators, and debuggers in creating and maintaining software. Provide examples of each tool and describe how they contribute to the efficiency and accuracy of software development.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "ex-long",
    chapter: 1,
  },
];

export { shortQuestions1, longQuestions1 };
