const shortQuestions = [
  { 
    id: 1, 
    question: "Define mean. Also write its formula.", 
    index: true, 
    trim: true, 
    type: "normal",
    category: "short",
    chapter: 5,
  },
  { 
    id: 2, 
    question: "What is meant by measures of central tendency? Also write their names.", 
    index: true, 
    trim: true,
    type: "important", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 3, 
    question: "Define median. Also write its formula.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 4, 
    question: "Define mode.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 5, 
    question: "What is meant by measures of dispersion? Also write their names.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 6, 
    question: "Define variance. Also write its formula.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 7, 
    question: "Define standard deviation. Also write its formula.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 8, 
    question: "Define probability. Also write its formula.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 9, 
    question: "What is meant by data collection and preparation? Write some data collection methods.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 10, 
    question: "What is meant by survey for data collection? Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 11, 
    question: "What is meant by experiments for data collection? Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 12, 
    question: "What is meant by observations for data collection? Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 13, 
    question: "Write a short note on data cleaning and transformation.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 14, 
    question: "What is meant by data cleaning?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 15, 
    question: "What is meant by data transformation?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 16, 
    question: "How can we handle missing data? Describe the methods of handling missing data.", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 17, 
    question: "What is the importance of data collection and preparation?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 18, 
    question: "What is the importance of data cleaning and transformation?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 19, 
    question: "Difference between median and mean.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 20, 
    question: "Difference between variance and probability.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 21, 
    question: "What is meant by data visualization?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 22, 
    question: "Name some types of data visualization.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 23, 
    question: "Define bar charts. Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 24, 
    question: "Define line graphs. Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 25, 
    question: "Define histograms. Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 26, 
    question: "Define scatter plots. Also give example.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 27, 
    question: "What is the importance of data visualization?", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 28, 
    question: "Write a short note on tools for data visualization.", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 29, 
    question: "What is the use of Excel and Google Sheets for visualization?", 
    index: true, 
    trim: true, 
    type: "normal", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 30, 
    question: "What are the steps of creating and interpreting visualizations?", 
    index: true, 
    trim: true, 
    type: "important", 
    category: "short",
    chapter: 5,
  },
  { 
    id: 31,
    question: "List two types of data visualization and describe when you would use each.",
    index: true,
    trim: true,
    type: "normal",
    category: "ex-short",
    chapter: 5,
  },
  { 
    id: 32,
    question: "How does visualizing data help in descriptive statistics?",
    index: true,
    trim: true,
    type: "important",
    category: "ex-short",
    chapter: 5,
  },
];

const longQuestions = [
  { 
    id: 1,
    question: "Discuss the types of data visualizations and their uses.", 
    index: true, 
    trim: true, 
    type: "important",
    category: "ex-long",
    chapter: 5,
  },
  { 
    id: 2, 
    question: "Discuss the concept of measures of central tendency with examples.", 
    index: true, 
    trim: true, 
    type: "important",
    category: "ex-long",
    chapter: 5,
  },
  { 
    id: 3, 
    question: "Explain data collection methods in detail.", 
    index: true, 
    trim: true, 
    type: "important",
    category: "ex-long",
    chapter: 5,
  },
  { 
    id: 4, 
    question: "Explain data cleaning and transformation in detail.", 
    index: true, 
    trim: true, 
    type: "normal",
    category: "ex-long",
    chapter: 5,
  }
];

export { shortQuestions, longQuestions };
